### ISSUE TITLE
Not able to run the py-smartreply

### ISSUE THREAD

**Issue by krototype** [Narasimha1997/py-smartreply#1]
Hi, I am trying to run this application, so that I can hit the API. For that I cloned the repo and I have run _python3 setup.py bdist_wheel_.
Now when I am trying to run pip install py-smartreply, I am getting the below mentioned error
_ERROR: Could not find a version that satisfies the requirement py_smartreply (from versions: none)
ERROR: No matching distribution found for py_smartreply_

1. I don't know whether I have to run the pip install thing if I have already cloned the repo. If so, what could be the problem here?
2. while running python3 web-server/app.py, I keep getting 
_Traceback (most recent call last):
  File "web-server/app.py", line 2, in <module>
    from smartreply import SmartReplyRuntime
ModuleNotFoundError: No module named 'smartreply'_

Can you please suggest, what I am doing wrong here? Thanks in advance!

**Comment by Narasimha1997** [comment]
@krototype 
Hi, 

What is the status of build? If it's successful you should see `.whl` files generated under `dist/` folder. Then you can install the wheel file as 

`pip3 install dist/*.whl` or you can install any wheel file you need from that directory.

**Comment by krototype** [comment]
Thanks, @Narasimha1997 for the help, didn't expect such a quick reply!!
